[tool.poetry]
name = "learningmodel"
version = "0.0.1"
description = "Thinking about model structure"
authors = ["David Shipman <dshipman@gmail.com>"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
