[tool.poetry]
name = "learningpackage"
version = "0.0.1"
description = "A package for learning about packages"
authors = ["David Shipman <dshipman@gmail.com>"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
